yarnPath: .yarn/releases/yarn-3.2.1.cjs
pnpMode: loose
pnpFallbackMode: all
packageExtensions:
  # Workaround for zero-installs
  # https://github.com/chalk/chalk/issues/531
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2
  debug@*:
    dependencies:
      supports-color: "*"
