nodeLinker: pnp

packageExtensions:
  "@blueprintjs/datetime@*":
    dependencies:
      "@types/react": ^18||^19
  "@types/react@*":
    dependencies:
      prop-types: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  node-fetch@*:
    dependencies:
      "@types/node": "*"
  ui-box@*:
    dependencies:
      "@types/prop-types": "*"
      csstype: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.13.0.cjs
