packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  "@blueprintjs/datetime@*":
    dependencies:
      "@types/react": "^16||^17||^18"
  "@parcel/fs@^2.13.3":
    dependencies:
      "@parcel/core": "^2.13.3"
  "@parcel/workers@^2.13.3":
    dependencies:
      "@parcel/core": "^2.13.3"
  "node-fetch@*":
    dependencies:
      "@types/node": "*"
  "ui-box@*":
    dependencies:
      "@types/prop-types": "*"
      "csstype": "*"
  "@types/react@*":
    dependencies:
      "prop-types": "*"

# We could make this stricter if we wanted to ensure correctness
# https://yarnpkg.com/configuration/yarnrc

pnpFallbackMode: all
pnpMode: loose

yarnPath: .yarn/releases/yarn-4.6.0.cjs
