packageExtensions:
  "@blueprintjs/datetime@*":
    dependencies:
      "@types/react": ^16||^17||^18
  "@parcel/fs@^2.13.3":
    dependencies:
      "@parcel/core": ^2.13.3
  "@parcel/workers@^2.13.3":
    dependencies:
      "@parcel/core": ^2.13.3
  "@types/react@*":
    dependencies:
      prop-types: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  node-fetch@*:
    dependencies:
      "@types/node": "*"
  ui-box@*:
    dependencies:
      "@types/prop-types": "*"
      csstype: "*"
  vite@*:
    dependencies:
      supports-color: "*"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.10.3.cjs
