packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"


pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.5.0.cjs
