packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  "@blueprintjs/datetime@*":
    dependencies:
      "@types/react": "^16||^17||^18"

# We could make this stricter if we wanted to ensure correctness
# https://yarnpkg.com/configuration/yarnrc


pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.6.0.cjs
