#!/usr/bin/env zsh

fn=$PROJECT_DIR/versioned/Products/webroot
query_dir="$fn/sections/queries"
image_dir="$fn/sections/images"
mkdir -p $fn $query_dir

rm -rf node_modules/.cache

# Serialize query datasets
./serialize-queries $query_dir

rm -f "$image_dir"
ln -s \
  "$NAUKLUFT_DATA_DIR/Sections/Digitized Images/web-images" \
  "$image_dir"

# Compile code
mkdir -p $fn/map
cp app/web-index.html $fn/index.html
cp app/entrypoints/sections-index.html $fn/sections/index.html
cp app/entrypoints/map-index.html $fn/map/index.html

webpack $@
## Use --watch flag to start browserSync

# Move images (and later, slice up)
tl copy mbtiles://$REPO_DIR/Products/tiles/geology.mbtiles file://$fn/map/tiles
