#!/usr/bin/env zsh
# Convert all stylus files in this repository to sass

# Find and iterate through stylus files
find . -name "*.styl" | while read -r file; do
  # Get the file name without the extension
  filename=$(basename "$file" .styl)
  echo $file

  # Convert the file
  #stylus2sass "$file" > "./src/styles/$filename.scss"
done