#!/usr/bin/env zsh
# Convert all stylus files in packages directory to sass

cd packages

# Find and iterate through stylus files
find . -name "*.styl" | while read -r file; do
  # Get the file name without the extension
  basename=${file:r}
  echo ${file:h}

  # If we've already converted this file, skip it
  if [[ -f "${basename}.scss" ]]; then
    continue
  fi

  yarn exec stylus --ext .scss "$file" -o "${file:h}"
  # Convert the file
  #stylus2sass "$file" > "./src/styles/$filename.scss"


done

find . -name "*.styl" | while read -r file; do
  # Get the file name without the extension
  basename=${file:r}
  # If we've already added .old.styl to this file, skip it
  if [ ${basename:t} = "old" ]; then
    continue
  fi

  mv "$file" "${basename}.old.styl" 
  # Convert the file
  #stylus2sass "$file" > "./src/styles/$filename.scss"


done

# Find and replace all stylus imports with sass imports
find . -name "*.ts" | while read -r file; do
  # Replace stylus import statements with scss
  sed -i 's/\.styl/\.scss/g' "$file"
done
