name: Static Website Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: [main, build-website-workflow]

jobs:
  test:
    name: Static Website Build
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Debug vars
        run: |
          echo "S3_BUCKET: ${{ vars.S3_BUCKET }}"
          echo "S3_PATH: ${{ vars.S3_PATH }}"
          echo "S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}"
          echo "S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}"
          echo "S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}"
