name: Static Website Build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  push:
    branches: [main]

env:
  VITE_MAPBOX_API_TOKEN: ${{ secrets.VITE_MAPBOX_API_TOKEN }}

jobs:
  test:
    name: Static website build
    runs-on: ubuntu-latest
    environment: development
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Pin react-docgen version
        run: yarn add -D react-docgen@7.0.0

      - name: Install dependencies
        run: |
          yarn install

      - name: Build storybook
        run: |
          yarn run build:storybook

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_PATH: ${{ vars.S3_PATH }}
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          VITE_MAPBOX_API_TOKEN: ${{ secrets.VITE_MAPBOX_API_TOKEN }}
        run: |
          echo "Uploading to S3 bucket: $S3_BUCKET" 
          rclone sync ./storybook-static \
            :s3:"$S3_BUCKET/$S3_PATH" \
            --s3-provider=Ceph \
            --s3-endpoint="$S3_ENDPOINT" \
            --s3-access-key-id="$S3_ACCESS_KEY" \
            --s3-secret-access-key="$S3_SECRET_KEY"