name: Build and deploy Storybook

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "storybook"
  cancel-in-progress: false

on:
  push:
    branches: [main]

env:
  VITE_MAPBOX_API_TOKEN: ${{ secrets.VITE_MAPBOX_API_TOKEN }}

jobs:
  deploy-storybook:
    name: Build and deploy storybook
    runs-on: ubuntu-latest
    environment: development
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          yarn install

      - name: Build storybook
        run: |
          yarn run build:storybook

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload to S3
        env:
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_PATH: ${{ vars.S3_PATH }}
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          VITE_MAPBOX_API_TOKEN: ${{ secrets.VITE_MAPBOX_API_TOKEN }}
        run: |
          echo "Uploading to S3 bucket: $S3_BUCKET" 
          rclone sync ./storybook-static \
            :s3:"$S3_BUCKET/$S3_PATH" \
            --s3-provider=Ceph \
            --s3-endpoint="$S3_ENDPOINT" \
            --s3-access-key-id="$S3_ACCESS_KEY" \
            --s3-secret-access-key="$S3_SECRET_KEY"

  # We will eventually want to publish packages to NPM, but for now we just prepare them.
  prepare-releases:
    name: Prepare releases
    runs-on: ubuntu-latest
    env:
      # Ensure that Chalk uses colors in the output
      FORCE_COLOR: 2
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          yarn install

      - name: Build all packages
        run: |
          yarn run build

      - name: Prepare releases
        run: |
          yarn run prepare
