name: Build storybook

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build storybook - test
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          yarn install

      - name: Build storybook
        run: |
          yarn run build:storybook

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
